# Generated by Django 4.0.3 on 2022-04-22 15:40

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.IntegerField(primary_key='true', serialize=False)),
                ('bname', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
            ],
            managers=[
                ('addbook', django.db.models.manager.Manager()),
            ],
        ),
    ]
